mcqs/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls import url


urlpatterns = [
    path('', index, name='index'),
    path('login', user_login,name="login"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout,name="logout"),
    path('signup', signup, name='signup'),
    path('forms', FormList.as_view(), name='forms'),
    path('addform', FormCreate.as_view(), name='addform'),
    path('updateform/<int:pk>', FormUpdate.as_view(), name='updateform'),
    path('detailform/<int:pk>/detail', FormDetail.as_view(), name='detailform'),
    path('deleteform/<int:pk>/delete', FormDelete.as_view(), name='deleteform'),
    path('detailform/<int:pk>/addquestion', QuestionCreate.as_view(), name='addquestion'),
    path('detailform/<int:pk2>/deletequestion/<int:pk>', QuestionDelete.as_view(), name='deletequestion'),
    path('detailform/<int:pk2>/updatequestion/<int:pk>', QuestionUpdate.as_view(), name='updatequestion'),
    path('detailform/<int:pk>/addmcq', McqCreate.as_view(), name='addmcq'),
    path('detailform/<int:pk2>/deletemcq/<int:pk>', McqDelete.as_view(), name='deletemcq'),
    path('detailform/<int:pk2>/updatemcq/<int:pk>', McqUpdate.as_view(), name='updatemcq'),
    path('detailform/<int:pk2>/mcq/<int:pk>/addchoice', addchoice.as_view(), name='addchoice'),
    path('formfill/<int:pk>', renderform.as_view(), name='formfill'),
    path('submissions', SubmissionList.as_view(), name='submissions'),
    path('submissions/<int:pk>/detail', SubmissionDetail.as_view(), name='detailsubmission'),
    path('submissions/<int:pk>/delete',SubmissionDelete.as_view(), name='deletesubmission'),
    url('', include('django.contrib.auth.urls')),
    path('pdfd/<int:id>', pdfMaker, name='PdfMaker'),
    path('csvd/<int:id>', csvMaker, name='CsvMaker')
]

question/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcqs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

admin.site.site_header = "AllianceTek"
admin.site.site_title = "AllianceTek Admin Portal"
admin.site.index_title = "Welcome to AllianceTek Researcher Portal"

mcqs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class choice(models.Model):
    name = models.CharField(max_length=100, default="test")

    def __str__(self):
        return self.name


class mcq(models.Model):
    question = models.CharField(max_length=500, default="")
    choices = models.ManyToManyField(choice)
    answer = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.question

    def get_cname(self):
        return 'mcq'


class questions(models.Model):
    question = models.CharField(max_length=500, default="")
    image = models.ImageField(upload_to='image/', blank=True, null=True, default="")
    Attachment = models.FileField(upload_to='files/', blank=True,  null=True, default="")
    answer = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.question

    def get_cname(self):
        return 'question'


class myForm(models.Model):
    name = models.CharField(max_length=100, default="Question Survey")
    mcqs = models.ManyToManyField(mcq)
    questions = models.ManyToManyField(questions)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detailform', kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse('updateform', kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse('deleteform', kwargs={"pk": self.pk})


class submission(models.Model):
    submittedby = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="Question Survey")
    mcqs = models.ManyToManyField(mcq)
    questions = models.ManyToManyField(questions)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detailsubmission', kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse('deletesubmission', kwargs={"pk": self.pk})


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)
    #signup_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User, dispatch_uid='save_new_user_profile')
def save_profile(sender, instance, created, **kwargs):
    user = instance
    if created:
        profile = Profile(user=user)
        profile.save()

mcqs/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import *
from django.contrib.auth.forms import UserCreationForm


class UserLoginForm(forms.Form):
    query=forms.CharField(label="Username",widget=forms.TextInput(attrs={'type':'text','class':'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'type':'password','class':'form-control'}))

    def clean(self,*args,**kwargs):
        username=self.cleaned_data.get("query")
        password=self.cleaned_data.get("password")
        user=authenticate(username=username,password=password)
        if user:
            self.cleaned_data["user_obj"]=user
        else:
            raise forms.ValidationError("Invalid Creditional")
        return super(UserLoginForm,self).clean(*args,**kwargs)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class myFormForm(forms.ModelForm):
    class Meta:
        model=myForm
        fields=('name',)


class questionForm(forms.ModelForm):
    class Meta:
        model=questions
        fields=('question', 'image', 'Attachment')


class mcqForm(forms.ModelForm):
    class Meta:
        model=mcq
        fields=('question',)

mcqs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, FileResponse

from .forms import UserLoginForm, myFormForm, questionForm, mcqForm, SignUpForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, get_user_model, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from .models import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views import View
import json
from django.middleware import csrf
from django.template.loader import get_template
from fpdf import FPDF, HTMLMixin
import csv


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        forms = myForm.objects.all()
        context = {'forms': forms}
        return render(request, 'home.html', context)
    else:
        return redirect('/login')


class renderform(View):
    def get(self, *args, **kwargs):
        context = {"object": myForm.objects.get(pk=self.kwargs['pk']), 'csrf_token': csrf.get_token(self.request)}
        return render(self.request, 'form.html', context)

    def post(self, *args, **kwargs):
        error = False
        try:
            obj = myForm.objects.get(pk=self.kwargs['pk'])
            newsubmission = submission(name=obj.name, submittedby=self.request.user)
            newsubmission.save()
            for q in obj.questions.all():
                answer = self.request.POST['question-' + str(q.pk)]
                newq = questions(question=q.question, answer=answer)
                newq.save()
                newsubmission.questions.add(newq)
            for m in obj.mcqs.all():
                answer = self.request.POST['mcq-' + str(m.pk)]
                newq = mcq(question=m.question, answer=answer)
                newq.save()
                newsubmission.mcqs.add(newq)
        except:
            error = True
        context = {"error": error}
        return render(self.request, 'submission.html', context)


def user_login(request, *args, **kwargs):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        user_obj = form.cleaned_data.get("user_obj")
        c = login(request, user_obj)
        return HttpResponseRedirect('/')
    else:
        pass
    return render(request, "login.html", {"form": form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.profile.email = form.cleaned_data.get('email')
            print(form.cleaned_data.get('email'))
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect("/")


class SubmissionList(ListView):
    model = submission
    template_name = 'Submissions/list.html'


class SubmissionDetail(DetailView):
    model = submission
    template_name = 'Submissions/detail.html'


class SubmissionDelete(DeleteView):
    model = submission
    template_name = 'Submissions/delete.html'
    success_url = '/submissions'


class FormList(ListView):
    model = myForm
    template_name = 'Forms/list.html'


class FormCreate(CreateView):
    form_class = myFormForm
    template_name = 'Forms/create.html'
    success_url = '/forms'


class FormUpdate(UpdateView):
    model = myForm
    form_class = myFormForm
    template_name = 'Forms/update.html'
    success_url = '/forms'


class FormDetail(DetailView):
    model = myForm
    template_name = 'Forms/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(FormDetail, self).get_context_data(*args, **kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class FormDelete(DeleteView):
    model = myForm
    template_name = 'Forms/delete.html'
    success_url = '/forms'


class QuestionCreate(CreateView):
    form = questionForm
    template_name = 'Questions/create.html'
    fields = ('question', 'image', 'Attachment')

    def get_queryset(self):
        new_context = questions.objects.all()
        return new_context

    def form_valid(self, form):
        form.save()
        myform = myForm.objects.get(pk=self.kwargs['pk'])
        myform.questions.add(form.instance)
        return HttpResponseRedirect(reverse('detailform', kwargs={"pk": self.kwargs['pk']}))


class QuestionDelete(DeleteView):
    model = questions
    template_name = 'Questions/delete.html'
    success_url = '/forms'

    def delete(self, request, *args, **kwargs):
        x = super(QuestionDelete, self).delete(request, *args, **kwargs)
        return HttpResponseRedirect(reverse('detailform', kwargs={"pk": self.kwargs['pk2']}))


class QuestionUpdate(UpdateView):
    model = questions
    form_class = questionForm
    template_name = 'Questions/update.html'
    success_url = '/forms'

    def get_success_url(self):
        return reverse('detailform', kwargs={"pk": self.kwargs['pk2']})


class McqCreate(CreateView):
    form = mcqForm
    template_name = 'MCQS/create.html'
    fields = ('question',)

    def get_queryset(self):
        new_context = mcq.objects.all()
        return new_context

    def form_valid(self, form):
        form.save()
        myform = myForm.objects.get(pk=self.kwargs['pk'])
        myform.mcqs.add(form.instance)
        return HttpResponseRedirect(reverse('detailform', kwargs={"pk": self.kwargs['pk']}))


class McqDelete(DeleteView):
    model = mcq
    template_name = 'MCQS/delete.html'
    success_url = '/forms'

    def get_success_url(self):
        return reverse('detailform', kwargs={"pk": self.kwargs['pk2']})


class McqUpdate(UpdateView):
    model = mcq
    form_class = mcqForm
    template_name = 'MCQS/update.html'
    success_url = '/forms'

    def get_success_url(self):
        return reverse('detailform', kwargs={"pk": self.kwargs['pk2']})


class addchoice(View):
    def post(self, *args, **kwargs):
        data = json.loads(self.request.body.decode('utf8').replace("'", '"'))
        try:
            newchoice = choice(name=data['value'])
            newchoice.save()
            currentmcq = mcq.objects.get(pk=data['id'])
            currentmcq.choices.add(newchoice)
            return HttpResponse('ok')
        except:
            return HttpResponse('failed')


def pdfMaker(request, id):
    class MyFPDF(FPDF, HTMLMixin):
        pass

    pdf = MyFPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    Submissions = submission.objects.filter(pk=id)

    for sub in Submissions:
        pdf.cell(200, 10, txt=f"{sub.name}", ln=1, align="C")
        pdf.cell(200, 10, txt="", ln=1, align="C")

        pdf.cell(200, 10, txt=f"QUESTIONS", ln=1, align="C")
        pdf.cell(200, 10, txt="", ln=1, align="C")

        for idx, ques in enumerate(sub.questions.all()):
            pdf.cell(200, 6, txt=f"{idx+1} - {ques}", ln=1, align="L")
            pdf.cell(200, 6, txt=f"Answer. {ques.answer}", ln=1, align="L")
            pdf.cell(200, 10, txt=" ", ln=1, align="L")

        pdf.cell(200, 10, txt=f"MCQS", ln=1, align="C")
        pdf.cell(200, 10, txt="", ln=1, align="C")
        
        for idx, mcq in enumerate(sub.mcqs.all()):
            pdf.cell(200, 6, txt=f"{idx+1} - {mcq}", ln=1, align="L")
            pdf.cell(200, 6, txt=f"Answer: {mcq.answer}", ln=1, align="L")
            pdf.cell(200, 10, txt=" ", ln=1, align="L")    

    pdf.output("submission.pdf")

    with open("submission.pdf", "rb") as f:
        response = HttpResponse(f.read(), content_type="application/pdf")
        response['Content-Disposition'] = 'inline; filename=submission.pdf'
        return response


def csvMaker(request, id):
    Submissions = submission.objects.filter(pk=id)
    with open('submission.csv', 'w', newline='') as file:
        writer = csv.writer(file)

        for sub in Submissions:
            for ques in sub.questions.all():
                writer.writerow([ques, ques.answer])
            for mcq in sub.mcqs.all():
                writer.writerow([mcq, mcq.answer])
        file.close()

    with open("submission.csv", "rb") as f:
        response = HttpResponse(f.read(), content_type="application/vnd.ms-excel")
        response['Content-Disposition'] = 'inline; filename=submission.csv'
        return response

mcqs/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
  <title>Questions</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <style type="text/css">
  body,html{
    min-height: 100vh;
    width: 100%;
  }
  .content{
      margin:0px !important;
      margin-top:20px;
      padding:0px;
      margin-left:-3%;
  }
  .nav{
      padding-top: 10px;
      padding-left: 5%;
      padding-right: 5%;
  }
  .row{
      margin: 0px !important;
      width:100%;
  }
  </style>
  {% block style%}
  {% endblock %}
</head>
<body>
  <div class="row header">
      <nav class="navbar navbar-default">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="navitem name" href="/">Home</a></li>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li><a class="navitem name" href=" {% url 'forms'%}">Forms</a></li>
                            <li><a class="navitem name" href=" {% url 'submissions'%}">Submissions</a></li>
                        {% elif perms.mcqs.add_myform %}
                            <li><a class="navitem name" href=" {% url 'forms'%}">Forms</a></li>
                        {%endif%}
                    <li><a class="navitem name" href=" {% url 'logout'%}">Logout</a></li>     
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li style="height:28px;"><a class="navbar-brand navitem name" href="/">Purism</a></li>
                    <li><a class="navbar-brand navitem name" href="#">{{ user.username }}</a></li>
                </ul>
            </div>
        </nav>
  </div>
    <div class="row main">
        <div class="col-sm-12 col-xs-12 content">
                {% block content %}
                {% endblock %}
        </div>
    </div>
</body>

</html>

mcqs/templates/form.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        <h1> Fill the Form</h1>
        <h2> {{object}}</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        <ul class="list-group">
            {% if object.questions.all|length > 0 and object.mcqs.all|length > 0%}
            <form method="Post" action="{% url 'formfill' pk=object.pk%}">
                {% csrf_token %}
                {%for q in object.questions.all%}
                <li class="list-group-item" >
                    {{q}}
		    {% if q.image %}
                        <img src="/media/{{ q.image }}" style="width : 100px; height : 100px"/>
                    {% endif %}
                    {% if q.Attachment %}
                        <a href="/media/{{ q.Attachment }}" >Attachement</a>
                    {% endif %}
                    <input name='question-{{q.pk}}' type='text' style="width:100%;" required/>
                </li>
                
                {%endfor%}
                {%for q in object.mcqs.all%}
                <li class="list-group-item" >
                    {{q}}
                    <select name='mcq-{{q.pk}}' type='text' style="width:100%;" required>
                        {%for c in q.choices.all%}
                            <option value="{{c}}">{{c}}</option>
                        {%endfor%}
                    </select>
                </li>
                
                {%endfor%}
                <li class="list-group-item" >
                    <input type='submit' value='Submit' class="btn btn-info btn-primary custombtn" >
                </li>
            </form>
            {% else %}
                <li class="list-group-item" >
                    No questions added in this Survey Yet
                </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

mcqs/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        <h1> Select your question form</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        <ul class="list-group">
        {%for obj in forms%}
        <li class="list-group-item" >
            <a href="{% url 'formfill' pk=obj.pk%}">{{forloop.counter}} - {{obj}}</a>
        </li>
        {%endfor%}
        </ul>
    </div>
</div>
{% endblock %}

mcqs/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        <h1> Login </h1>
        <form method="Post" action="/login">
            {% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='Login' class="btn btn-info btn-primary custombtn">
        </form>
        <br>
        <p>OR</p>
        <a href="/signup" class="btn btn-info btn-primary custombtn">
            Register
        </a>
        <a href="/password_reset/" class="btn btn-info btn-primary custombtn">
            Forgot Password
        </a>
    </div>
</div>
{% endblock %}

mcqs/templates/pdffile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mcqs/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
      <h2>Sign up</h2>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit">Sign up</button>
      </form>
    </div>
</div>
{% endblock %}

mcqs/templates/submission.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        <h1> Fill the Form</h1>
        <h2> {{object}}</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 text-left">
        {% if error%}
            <div class="alert alert-success">
                Failed to Submit Try Again
            </div>
        {% else %}
            <div class="alert alert-success">
                Submitted succesfully
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}